spring:
  cloud:
    stream:
      function:
        bindings:
          # Need to be aware of Spring bean name.
          # java.util.function.Consumer type bean name-in-0
          # process-in-0: input
          consumer-in-0: input
      bindings:
        # input refers and associates spring.cloud.stream.function.bindings.process-in-0=input
        input:
          # inbound queue topic name
          destination: string-pipe-2
